PACKAGE_VERSION="0.9"
PACKAGE_NAME="uniwill-laptop"
AUTOINSTALL="yes"

MAKE="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"
BUILT_MODULE_NAME[0]="uniwill-laptop"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86"
